import numpy as np
import astropy.units as u

voronoi_cells = {
    'AllowRefinement': '',
    'CenterOfMass': 'Coordinates',
    'Coordinates': 'Coordinates',
    'Density': 'Density',
    'ElectronAbundance': '',
    'EnergyDissipation': 'EnergyDissipation',
    'GFM_AGNRadiation': False,  # u.Unit('erg s^-1 cm^-2')*4*np.pi,
    'GFM_CoolingRate': u.Unit('erg cm^3 s^-1'),
    'GFM_Metallicity': '',
    'GFM_Metals': '',
    'GFM_WindDMVelDisp': u.Unit('arepo_velocity'),
    'GFM_WindHostHaloMass': 'Masses',
    'HighResGasMass': 'Masses',
    'InternalEnergy': 'InternalEnergy',
    'Machnumber': '',
    'MagneticField': 'MagneticField',
    'MagneticFieldDivergence': 'MagneticFieldDivergence',
    'MagneticFieldDivergenceAlternative': 'MagneticFieldDivergence',
    'Masses': 'Masses',
    'NeutralHydrogenAbundance': '',
    'ParticleIDs': '',
    'Potential': 'Potential',
    'StarFormationRate': u.Unit('Msun yr^-1'),
    'SubfindDMDensity': 'Density',
    'SubfindDensity': 'Density',
    'SubfindHsml': 'Coordinates',
    'SubfindVelDisp': u.Unit('arepo_velocity'),
    'Velocities': 'Velocities',
    'VelocityGradient': 'VelocityGradient'
}

dark_matter = {
    'Coordinates': 'Coordinates',
    'ParticleIDs': '',
    'Potential': False,
    'SubfindDMDensity': 'Density',
    'SubfindDensity': 'Density',
    'SubfindHsml': 'Coordinates',
    'SubfindVelDisp': u.Unit('arepo_velocity'),
    'Velocities': 'Velocities'
}

stars = {
    'Coordinates': 'Coordinates',
    'GFM_InitialMass': 'Masses',
    'GFM_Metallicity': '',
    'GFM_Metals': '',
    'GFM_StellarFormationTime': '',
    'GFM_StellarPhotometrics': False,
    'Masses': 'Masses',
    'ParticleIDs': '',
    'Potential': False,
    'SubfindDMDensity': 'Density',
    'SubfindDensity': 'Density',
    'SubfindHsml': 'Coordinates',
    'SubfindVelDisp': u.Unit('arepo_velocity'),
    'Velocities': 'Velocities'
}

energy_inj = u.Unit('small_a^2 small_h^-1 arepo_energy')

black_holes = {
    'BH_CumEgyInjection_QM': energy_inj,
    'BH_CumEgyInjection_RM': energy_inj,
    'BH_CumMassGrowth_QM': 'Masses',
    'BH_CumMassGrowth_RM': 'Masses',
    'BH_Density': 'Density',
    'BH_HostHaloMass': 'Masses',
    'BH_Hsml': 'Coordinates',
    'BH_MPB_CumEgyHigh': energy_inj,
    'BH_MPB_CumEgyLow': energy_inj,
    'BH_Mass': 'Masses',
    'BH_Mass_bubbles': 'Masses',
    'BH_Mass_ini': 'Masses',
    'BH_Mdot': u.Unit('arepo_mass / arepo_time'),
    'BH_MdotBondi': u.Unit('arepo_mass / arepo_time'),
    'BH_MdotEddington': u.Unit('arepo_mass / arepo_time'),
    'BH_Pressure': u.Unit('arepo_mass arepo_length^-1 arepo_time^-2'),
    'BH_Progs': '',
    'BH_U': u.Unit('arepo_velocity^2'),
    'Coordinates': 'Coordinates',
    'Masses': 'Masses',
    'ParticleIDs': '',
    'Potential': False,
    'SubfindDMDensity': 'Density',
    'SubfindDensity': 'Density',
    'SubfindHsml': 'Coordinates',
    'SubfindVelDisp': u.Unit('arepo_velocity'),
    'Velocities': 'Velocities'
}

groups = {
    'GroupBHMass': False,
    'GroupBHMdot': False,
    'GroupCM': False,
    'GroupFirstSub': False,
    'GroupGasMetalFractions': False,
    'GroupGasMetallicity': False,
    'GroupLen': False,
    'GroupLenType': False,
    'GroupMass': 'Masses',
    'GroupMassType': False,
    'GroupNsubs': False,
    'GroupPos': 'Coordinates',
    'GroupSFR': False,
    'GroupStarMetalFractions': False,
    'GroupStarMetallicity': False,
    'GroupVel': False,
    'GroupWindMass': False,
    'Group_M_Crit200': 'Masses',
    'Group_M_Crit500': 'Masses',
    'Group_M_Mean200': 'Masses',
    'Group_M_TopHat200': 'Masses',
    'Group_R_Crit200': 'Coordinates',
    'Group_R_Crit500': 'Coordinates',
    'Group_R_Mean200': 'Coordinates',
    'Group_R_TopHat200': 'Coordinates'
}

subhalos = {
    'SubhaloBHMass': False,
    'SubhaloBHMdot': False,
    'SubhaloBfldDisk': False,
    'SubhaloBfldHalo': False,
    'SubhaloCM': False,
    'SubhaloGasMetalFractions': False,
    'SubhaloGasMetalFractionsHalfRad': False,
    'SubhaloGasMetalFractionsMaxRad': False,
    'SubhaloGasMetalFractionsSfr': False,
    'SubhaloGasMetalFractionsSfrWeighted': False,
    'SubhaloGasMetallicity': False,
    'SubhaloGasMetallicityHalfRad': False,
    'SubhaloGasMetallicityMaxRad': False,
    'SubhaloGasMetallicitySfr': False,
    'SubhaloGasMetallicitySfrWeighted': False,
    'SubhaloGrNr': False,
    'SubhaloHalfmassRad': False,
    'SubhaloHalfmassRadType': False,
    'SubhaloIDMostbound': False,
    'SubhaloLen': False,
    'SubhaloLenType': False,
    'SubhaloMass': False,
    'SubhaloMassInHalfRad': False,
    'SubhaloMassInHalfRadType': False,
    'SubhaloMassInMaxRad': False,
    'SubhaloMassInMaxRadType': False,
    'SubhaloMassInRad': False,
    'SubhaloMassInRadType': False,
    'SubhaloMassType': False,
    'SubhaloParent': False,
    'SubhaloPos': False,
    'SubhaloSFR': False,
    'SubhaloSFRinHalfRad': False,
    'SubhaloSFRinMaxRad': False,
    'SubhaloSFRinRad': False,
    'SubhaloSpin': False,
    'SubhaloStarMetalFractions': False,
    'SubhaloStarMetalFractionsHalfRad': False,
    'SubhaloStarMetalFractionsMaxRad': False,
    'SubhaloStarMetallicity': False,
    'SubhaloStarMetallicityHalfRad': False,
    'SubhaloStarMetallicityMaxRad': False,
    'SubhaloStellarPhotometrics': False,
    'SubhaloStellarPhotometricsMassInRad': False,
    'SubhaloStellarPhotometricsRad': False,
    'SubhaloVel': False,
    'SubhaloVelDisp': False,
    'SubhaloVmax': False,
    'SubhaloVmaxRad': False,
    'SubhaloWindMass': False
}
