name: Build and publish Python wheels

on:
  release:
    types: [created]
  push:
    branches:
      - pypi

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux manylinux builds
          - os: ubuntu-latest
            arch: x86_64
            cibw_arch: x86_64
            setup_python: 3.10
          - os: ubuntu-latest
            arch: arm64
            cibw_arch: aarch64
            setup_python: 3.10
          # macOS builds
          - os: macos-13
            arch: x86_64
            cibw_arch: x86_64
            setup_python: 3.10
          - os: macos-13
            arch: arm64
            cibw_arch: arm64
            setup_python: 3.10

    steps:
      - uses: actions/checkout@v4

      # Setup Python (always 3.10 for safety on all architectures)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.setup_python }}
          architecture: ${{ matrix.arch }}

      # Install cibuildwheel
      - name: Install cibuildwheel
        run: pip install --upgrade pip cibuildwheel

      # Build wheels
      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*   # build for multiple Python versions
          CIBW_ARCHS_MACOS: ${{ matrix.cibw_arch }}
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_arch }}
          CIBW_BEFORE_BUILD: pip install cython numpy astropy scipy
          # CIBW_TEST_COMMAND: python -m unittest discover -v  # commented out
        timeout-minutes: 120

      # Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine check dist/*
          twine upload dist/*
