name: Build and publish Python wheels

on:
  release:
    types: [created]
  push:
    branches:
      - pypi

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # this sets a default for cibuildwheel

      # Install cibuildwheel
      - name: Install cibuildwheel
        run: pip install --upgrade pip cibuildwheel

      # Build wheels
      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-*
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_LINUX: x86_64 aarch64
          CIBW_BEFORE_BUILD: pip install cython numpy astropy scipy
          # CIBW_TEST_COMMAND: python -m unittest discover -v  # commented out
        timeout-minutes: 120

      # Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine check dist/*
          twine upload dist/*
